services:
 mongo-notifcations:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_notifcation_data:/data/db
    
 mysql-game:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_game_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-user:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 notifcation-service:
  depends_on:
    - mongo-notifcations
  # image: miverboven/product-service
  ports:
    - 8080:8080
  links:
    - mongo-notifcations
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-notifcations
   
 user-service:
  depends_on:
    - mysql-user
  # image: miverboven/inventory-service
  ports:
    - 8082:8082
  links:
    - mysql-user
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3307

 game-service:
  depends_on:
    - notifcation-service
    - user-service
  # image: miverboven/order-service
  ports:
    - 8081:8081
  links:
    - notifcation-service
    - user-service
  environment:
   NOTIFCATION_SERVICE_BASEURL: notifcation-service:8080
   USER_INFO_SERVICE_BASEURL: user-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-game
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - notifcation-service
     - game-service
   # image: miverboven/ede-api-gateway
   ports:
     - 8083:8083
   links:
     - notifcation-service
     - game-service
   environment:
     NOTIFCATION_SERVICE_BASEURL: notifcation-service:8080
     GAME_SERVICE_BASEURL: game-service:8081

volumes:
 mongodb_notifcation_data:
 mysql_user_data:
 mysql_game_data: