services:
  user-db:
    image: "mysql:latest"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "user_db"
    volumes:
      - "user-db-data:/var/lib/mysql"
    networks:
      - "bowling-network"

  game-db:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "game_db"
    volumes:
      - "game-db-data:/var/lib/mysql"
    networks:
      - "bowling-network"
 
  mongodb-notification:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    networks:
      - "bowling-network"

  api-gateway:
    build:
      context: "./api-gateway"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - "user-service"
      - "game-service"
      - "notification-service"
    environment:
      USER_SERVICE_URI: "user-service:8080"
      GAME_SERVICE_URI: "game-service:8080"
      NOTIFICATION_SERVICE_URI: "notification-service:8080"
    networks:
      - "bowling-network"
 
  user-service:
    build:
      context: "./user-service"
      dockerfile: "Dockerfile"
    ports:
      - "8081:8080"
    depends_on:
      - "user-db"
    environment:
      MYSQL_DB_HOST: "user-db"
      MYSQL_DB_PORT: "3306"
      MYSQL_DB_NAME: "game_db"
      MYSQL_DB_USERNAME: "root"
      MYSQL_DB_PASSWORD: "abc123"
    networks:
      - "bowling-network"

  game-service:
    build:
      context: "./game-service"
      dockerfile: "Dockerfile"
    ports:
      - "8082:8080"
    depends_on:
      - "game-db"
    environment:
      MYSQL_DB_HOST: "game-db"
      MYSQL_DB_PORT: "3306"
      MYSQL_DB_NAME: "game_db"
      MYSQL_DB_USERNAME: "root"
      MYSQL_DB_PASSWORD: "abc123"
    networks:
      - "bowling-network"

  notification-service:
    build:
      context: "./notification-service"
      dockerfile: "Dockerfile"
    ports:
      - "8083:8080"
    depends_on:
      - "mongodb-notification"
    environment:
      MONGODB_HOST: "mongodb-notification"
      MONGODB_PORT: "27017"
    networks:
      - "bowling-network"

volumes:
  user-db-data:
  game-db-data:
  mongo-data:

networks:
  bowling-network:
    driver: "bridge"
