services:

  #############
  # DATABASES #
  #############
  user-db:
    image: "mysql:latest"
    ports:
      - ":3306"
#      - "3307:3306" # DEVELOPMENT/ DBA ONLY
    environment:
      MYSQL_ROOT_USER: ${USER_DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
    volumes:
      - "user-db-data:/var/lib/mysql"
    networks:
      - "bowling-network"

  game-db:
    image: "mysql:latest"
    ports:
      - ":3306"
#      - "3306:3306" # DEVELOPMENT/ DBA ONLY
    environment:
      MYSQL_ROOT_USER: ${GAME_DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${GAME_DB_PASSWORD}
      MYSQL_DATABASE: ${GAME_DB_NAME}
    volumes:
      - "game-db-data:/var/lib/mysql"
    networks:
      - "bowling-network"
 
  notification-db:
    image: "mongo:latest"
    ports:
      - ":27017"
#      - "27017:27017" # DEVELOPMENT/ DBA ONLY
    volumes:
      - "mongo-data:/data/db"
    networks:
      - "bowling-network"


  ############
  # SERVICES #
  ############
  user-service:
    image: "bantonis96/user-service:latest"
    ports:
      - ":8080"
#      - "8081:8080" # DEVELOPMENT ONLY
    depends_on:
      - "user-db"
    environment:
      MYSQL_DB_HOST: ${USER_DB_HOST}
      MYSQL_DB_PORT: "3306"
      MYSQL_DB_NAME: ${USER_DB_NAME}
      MYSQL_DB_USERNAME: ${USER_DB_USERNAME}
      MYSQL_DB_PASSWORD: ${USER_DB_PASSWORD}
    networks:
      - "bowling-network"

  game-service:
    image: "bantonis96/game-service:latest"
    ports:
      - ":8080"
#      - "8082:8080" # DEVELOPMENT ONLY
    depends_on:
      - "game-db"
    environment:
      MYSQL_DB_HOST: ${GAME_DB_HOST}
      MYSQL_DB_PORT: "3306"
      MYSQL_DB_NAME: ${GAME_DB_NAME}
      MYSQL_DB_USERNAME: ${GAME_DB_USERNAME}
      MYSQL_DB_PASSWORD: ${GAME_DB_PASSWORD}
    networks:
      - "bowling-network"

  notification-service:
    image: "bantonis96/notification-service:latest"
    ports:
      - ":8080"
#      - "8083:8080" # DEVELOPMENT ONLY
    depends_on:
      - "notification-db"
    environment:
      MONGODB_HOST: ${NOTIFICATION_DB_HOST}
      MONGODB_PORT: "27017"
      MONGODB_DOCUMENT_NAME: ${NOTIFICATION_DB_NAME}
    networks:
      - "bowling-network"


  ###########
  # GATEWAY #
  ###########
  api-gateway:
    image: "bantonis96/api-gateway:latest"
    ports:
      - "8086:8080"
    depends_on:
#      - "keycloak"
      - "user-service"
      - "game-service"
      - "notification-service"
    restart: "on-failure"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      USER_SERVICE_URI: ${USER_SERVICE_URI}
      GAME_SERVICE_URI: ${GAME_SERVICE_URI}
      NOTIFICATION_SERVICE_URI: ${NOTIFICATION_SERVICE_URI}
#      API_GATEWAY_URI: ${API_GATEWAY_URI}
#      KEYCLOAK_URI: ${KEYCLOAK_URI}
#      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
#      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
#      OAUTH2_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
#      OAUTH2_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
#      OAUTH2_PROVIDER_URL: "http://${KEYCLOAK_URI}/realms/bowlingrealm"
#      SPRING_CLOUD_GATEWAY_KEYCLOAK_URI: "http://keycloak:8080"
    networks:
      - "bowling-network"


  ###########
  # KEYCLOAK #
  ###########
#  keycloak:
#    image: "quay.io/keycloak/keycloak:22.0.1"
#    environment:
#      KEYCLOAK_ADMIN: "admin"
#      KEYCLOAK_ADMIN_PASSWORD: "admin"
#      KC_DB: "dev-mem"
#      KC_HOSTNAME: "keycloak"
#      KC_HTTP_PORT: "8080"
#    ports:
#      - "8180:8080"
#    command: "start-dev"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://keycloak:8080/realms/bowlingrealm"]
#      interval: "30s"
#      timeout: "10s"
#      retries: 5
#    volumes:
#      - ./.init/keycloak-setup.sh:/opt/keycloak/keycloak-setup.sh
#    entrypoint: ["sh", "/opt/keycloak/keycloak-setup.sh"]
#    networks:
#      - "bowling-network"


###########
# VOLUMES #
###########
volumes:
  user-db-data:
  game-db-data:
  mongo-data:


############
# NETWORKS #
############
networks:
  bowling-network:
    driver: "bridge"
