server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  cloud:
    gateway:
      routes:
        # Route for the game-service
        - id: game-service
          uri: http://game-service:8081
          predicates:
            - Path=/api/games/**
          filters:
            - RewritePath=/api/games/(?<path>.*), /$\\{path}

        # Route for the user-service
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<path>.*), /$\\{path}

        # Route for the notification-service
        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<path>.*), /$\\{path}