server:
  port: 8080
  max-http-request-header-size: 160KB

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:

      routes:

#        # Route for the login
#        - id: login-route
#          uri: http://${API_GATEWAY_URI:localhost:8080}/login
#          predicates:
#            - Path=/api/auth/login

        # Route for the user-service
        - id: user-service
          uri: http://${USER_SERVICE_URI:localhost:8081}
          predicates:
            - Path=/api/user/**

        # Route for the game-service
        - id: game-service
          uri: http://${GAME_SERVICE_URI:localhost:8082}
          predicates:
            - Path=/api/game/**

        # Route for the notification-service
        - id: notification-service
          uri: http://${NOTIFICATION_SERVICE_URI:localhost:8083}
          predicates:
            - Path=/api/notification/**

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: ${KEYCLOAK_CLIENT_ID:bowling-api-gateway}
#            client-secret: ${KEYCLOAK_CLIENT_SECRET:bowling-api-gateway}
#            authorization-grant-type: password
#            scope: openid, profile
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://${KEYCLOAK_URI:localhost:8180}/realms/bowlingrealm
#            authorization-uri: http://${KEYCLOAK_URI:localhost:8180}/realms/bowlingrealm/protocol/openid-connect/auth
#            token-uri: http://${KEYCLOAK_URI:localhost:8180}/realms/bowlingrealm/protocol/openid-connect/token
#            user-name-attribute: preferred_username
#      resourceserver:
#        jwt:
#          issuer-uri: http://${KEYCLOAK_URI:localhost:8180}/realms/bowlingrealm
#          jwk-set-uri: http://${KEYCLOAK_URI:localhost:8180}/realms/bowlingrealm/protocol/openid-connect/certs
