server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  cloud:
    gateway:
      routes:
        # Route for the user-service
        - id: user-service
          uri: http://${USER_SERVICE_URI:user-service:8080}
          predicates:
            - Path=/api/user/**

        # Route for the game-service
        - id: game-service
          uri: http://${GAME_SERVICE_URI:game-service:8080}
          predicates:
            - Path=/api/game/**

        # Route for the notification-service
        - id: notification-service
          uri: http://${NOTIFICATION_SERVICE_URI:notification-service:8080}
          predicates:
            - Path=/api/notification/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: "gateway-client"
            client-secret: "very-safe-secret"
            authorization-grant-type: authorization_code
            scope: openid, profile, roles
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8180/realms/bowlingrealm
            authorization-uri: http://keycloak:8180/realms/bowlingrealm/protocol/openid-connect/auth
            token-uri: http://keycloak:8180/realms/bowlingrealm/protocol/openid-connect/token
            user-info-uri: http://keycloak:8180/realms/bowlingrealm/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8180/realms/bowlingrealm/protocol/openid-connect/certs
            user-name-attribute: preferred_username