server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  cloud:
    gateway:
      routes:

        # Route for the user-service
        - id: user-service
          uri: http://${USER_SERVICE_URI:user-service:8080}
          predicates:
            - Path=/api/user/**

        # Route for the game-service
        - id: game-service
          uri: http://${GAME_SERVICE_URI:game-service:8080}
          predicates:
            - Path=/api/game/**

        # Route for the notification-service
        - id: notification-service
          uri: http://${NOTIFICATION_SERVICE_URI:notification-service:8080}
          predicates:
            - Path=/api/notification/**